#! /bin/sh
# /etc/init.d/phidgets-temp-daemon
#
###############
# Configuration
###############

# Python executable path
PYTHON=/usr/bin/python

# phidget-temp-daemon run.py executable path
RUN=/opt/phidgets-temp-alarm/run.py

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting phidgets-temp-daemon"
    $PYTHON $RUN start
    ;;
  stop)
    echo "Stopping phidgets-temp-daemon"
    $PYTHON $RUN stop
    ;;
  *)
    $PYTHON $RUN $1
    exit 1
    ;;
esac

exit 0

